Add ability for bot to get xkcd comics
idoneam/Canary pull request #357
Opened 2020-11-21 21:55 UTC by namemcguffin

Adds ability for bot to fetch xkcd comics

## Description
Added one new function, ?xkcd, which sends an embed containing the xkcd comic requested, or the latest one if no number was specified

## Motivation and Context
Porting functionality from Mose

## How Has This Been Tested?
Tested in the idoneam test server

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2020-11-22 02:11 UTC, davidlougheed requested changes
probably don't need to preface all the variables with `xkcd_`, since theyre scoped in the function anyway

2020-11-22 02:11 UTC, davidlougheed commented on cogs/memes.py
> +        if xkcd_req.status_code == 200:
early return if not 200 since its the exception case

2020-11-22 02:11 UTC, davidlougheed commented on cogs/memes.py
> +from requests import get
i would probably just do `import requests` and use `requests.get` here to make the global namespace a bit less wierd

2020-11-22 02:11 UTC, davidlougheed commented on cogs/memes.py
> +from re import findall
same here for import

2020-11-22 02:11 UTC, davidlougheed commented on cogs/memes.py
> +from discord import Embed
same here for import

2020-11-22 02:11 UTC, davidlougheed commented on cogs/memes.py
> +                f"{xkcd_img_soup['alt']} (number: {findall(r'^https://xkcd.com/([1-9][0-9]*)/$', xkcd_soup.find('meta', property='og:url')['content'])[0]})"
this line is too long

2020-12-30 20:12 UTC, le-potate requested changes

2020-12-30 20:12 UTC, le-potate commented on cogs/memes.py
> +                f"xkcd number {xkcd_command} could not be found (request returned {xkcd_req.status_code})"
I'd write (#4) instead of (number: 4) here too

2020-12-30 20:12 UTC, le-potate commented on cogs/memes.py
> +        else:
check if the number is greater than 1

2020-12-30 20:12 UTC, le-potate commented on cogs/memes.py
> +        Valid options are: nothing, 'latest' and a positive integer greater than one and at most equal to the latest issue number.
i'd write "or" instead of "and"

2020-12-30 20:12 UTC, le-potate commented on cogs/memes.py
> +                f"xkcd number {xkcd_command} could not be found (request returned {xkcd_req.status_code})"
Actually why not send the latest instead if this happens

2020-12-30 21:28 UTC, le-potate commented on cogs/memes.py
> +            if xkcd_num < 0:
< 1

2020-12-30 21:32 UTC, le-potate approved these changes
looks good to me

2020-12-30 22:03 UTC, davidlougheed approved these changes

2020-12-30 22:07 UTC, merged