switch to black as autoformatter
idoneam/Canary pull request #418
Opened 2021-04-07 16:01 UTC by namemcguffin

switches to black as the autoformatter

## Description
- removed `.github/worflows/yapf.yml`
- added `.github/worflows/black.yml`
- added `.github/actions/black_check/Dockerfile` and `.github/actions/black_check/action.yml`

## Motivation and Context
YAPF's formatting consistently makes code less readable, especially when it comes to pipelines

## How Has This Been Tested?
tested on a private repo

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2021-04-25 15:20 UTC, jidicula requested changes
instead of rolling your own Dockerfile and using 2 separate actions, why not use Black's provided action? https://github.com/psf/black#github-actions

2021-04-25 15:23 UTC, jidicula commented on README.md
>   [![Discord](https://img.shields.io/discord/236668784948019202.svg)](https://discord.gg/HDHvv58)
```suggestion
 [![Discord](https://img.shields.io/discord/236668784948019202.svg)](https://discord.gg/HDHvv58)
 [![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
```

2021-05-02 23:53 UTC, jidicula approved these changes
LGTM ⚫

2021-07-25 14:56 UTC, davidlougheed requested changes

2021-07-25 14:56 UTC, davidlougheed commented on README.md
> + [![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
this line is duplicated?

2021-09-22 13:42 UTC, jidicula commented on README.md
> + [![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)
```suggestion
```

2021-12-02 02:50 UTC, davidlougheed approved these changes

2021-12-02 02:58 UTC, merged